apiVersion : apps/v1
kind: Deployment
metadata:
  name: "aks3-852c"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "aks3-852c"
  template:
    metadata:
      labels:
        app: "aks3-852c"
    spec:
      containers:
        - name: "aks3-852c"
          image: "gpreg3.azurecr.io/aks3"
          ports:
          - containerPort: 80